import type { Metadata } from "next";
import "./globals.css";
import "stream-chat-react/dist/css/index.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/Providers/theme-provider";
import { ClerkSync } from "@/components/clerk-sync";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans"
      )}
    >
      <body className="h-full flex flex-col">
        <ClerkProvider
          localization={{
            signUp: {
              start: {
                title: "Create your ShubhGPT account",
              },
            },
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkSync />
            {children}
          </ThemeProvider>
          <Toaster />
        </ClerkProvider>
      </body>
    </html>
  );
}
